### PR TITLE
Fix/user defaults

### PR DESCRIPTION
**Pull request by petropavel13**
merge after https://github.com/TouchInstinct/LeadKit/pull/53

### CODE REVIEW

**Comment by NikAshanin** [comment]
If you fix linters than before it should be updated?
https://github.com/TouchInstinct/Styleguide/blob/master/ios/Examples/.swiftlint.yml

**Comment by petropavel13** [comment]
just update local version of linters. config files not touched

**Comment by NikAshanin** [comment]
mm? take new version of swiftlint.yml and fix it in leadkit?

**Comment by NikAshanin** [comment]
and, also, please, update cocoalumberjack version to 3.1.0

**Comment by petropavel13** [comment]
After upgrading cocoalumberjack version to 3.1.0. I got: `LogFormatter.swift:26:21: Use of undeclared type 'DDDispatchQueueLogFormatter'`
I have no idea how to correctly fix that.
Since is it your code, please fix it by yourself @NikAshanin

**Pull request merged**
